PACKAGE_NAME="karya-intel-block"
PACKAGE_VERSION="1.0.0"
BUILT_MODULE_NAME[0]="karya-intel-block"
DEST_MODULE_LOCATION[0]="/kernel/drivers/karya"
BUILT_MODULE_LOCATION[0]="."
MAKE="make all"
CLEAN="make clean"
AUTOINSTALL="yes"
REMAKE_INITRD="yes"
