[options]
Architecture = auto
HoldPkg = pacman glibc
SyncFirst = archlinux-keyref
SigLevel = Required DatabaseOptional
LocalFileSigLevel = Optional

[karya-de]
Server = https://github.com/muhammetodosks/$repo/releases/download/latest
SigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[community]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist
